version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: <ODA2MjcwNjc4ODczNDA3NTQ4.YBnAFQ.t-uyVEMiK6kugloGZZr3wJAcOck>
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <806173899132764201>