version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: <RA_-A2Y63qlaBFj_du0oz2sjTrubgwtvn>
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <your-logging-textchannel-id-as-integer>
